const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000'
export async function saveChallenge(challenge) { const payload = { ...challenge, affected_people: challenge.affectedPeople || '' }; const response = await fetch(`${API_BASE_URL}/api/challenges`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error('Challenge persistence unavailable'); return response.json() }
export async function saveSolution(solution) { const response = await fetch(`${API_BASE_URL}/api/solutions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(solution) }); if (!response.ok) throw new Error('Solution persistence unavailable'); return response.json() }
export async function submitChallenge(challenge) { const response = await fetch(`${API_BASE_URL}/api/challenges/analyze`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(challenge) }); if (!response.ok) throw new Error(`Request failed with status ${response.status}`); return response.json() }
export async function findSimilarChallenges(challenge) { const response = await fetch(`${API_BASE_URL}/api/challenges/similar`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(challenge) }); if (!response.ok) throw new Error('Similarity analysis unavailable'); return response.json() }
export async function assessImpact(challenge) { const response = await fetch(`${API_BASE_URL}/api/challenges/impact`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(challenge) }); if (!response.ok) throw new Error('Impact analysis unavailable'); return response.json() }
export async function getSolutions(challenge) { const response = await fetch(`${API_BASE_URL}/api/challenges/solutions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(challenge) }); if (!response.ok) throw new Error('Solution recommendations unavailable'); return response.json() }
export async function getUniversityMatches(challenge) { const response = await fetch(`${API_BASE_URL}/api/challenges/universities`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(challenge) }); if (!response.ok) throw new Error('University matching unavailable'); return response.json() }
export async function getIndustryMatches(challenge) { const response = await fetch(`${API_BASE_URL}/api/challenges/industries`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(challenge) }); if (!response.ok) throw new Error('Industry matching unavailable'); return response.json() }
