import { ArrowLeft, ArrowRight, CheckCircle2, CircleDashed, LoaderCircle } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import Navbar from '../components/Navbar'
import { assessImpact } from '../services/api'

const labels = { communityReach: 'Community Reach', urgency: 'Urgency', resourceSensitivity: 'Resource Sensitivity', domainImportance: 'Domain Importance', problemSeverity: 'Problem Severity' }
function Impact() {
  const [challenge] = useState(() => JSON.parse(sessionStorage.getItem('neuroxChallenge') || 'null'))
  const [impact, setImpact] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(Boolean(challenge))
  const loadImpact = useCallback(async () => { if (!challenge) return; setError(''); try { const data = await assessImpact(challenge); setImpact(data.impact) } catch { setError('Impact analysis is temporarily unavailable.') } finally { setLoading(false) } }, [challenge])
  useEffect(() => { const timer = window.setTimeout(loadImpact, 0); return () => window.clearTimeout(timer) }, [loadImpact])
  const explanation = impact && `This challenge has ${impact.level.toLowerCase()} preliminary impact because it combines ${impact.factors.communityReach}% community reach with ${impact.factors.domainImportance}% domain importance. These prototype signals are transparent assumptions, not a scientific prediction.`
  const retry = () => { setLoading(true); loadImpact() }
  return <div className="app-shell form-shell"><Navbar /><main className="analysis-page container"><Link className="back-link" to="/similar"><ArrowLeft size={16} />Back to Similar Challenges</Link><div className="analysis-heading"><p className="eyebrow"><span />NEUROX IMPACT ANALYSIS</p><h1>Preliminary Impact Assessment</h1><p>A transparent prototype score based on the submitted challenge details.</p></div>{loading ? <section className="analysis-card loading-card"><LoaderCircle className="spinner" size={30} /><h2>NeuroX is assessing potential impact...</h2></section> : error ? <section className="analysis-card empty-analysis"><h2>{error}</h2><p>Please try again.</p><button className="button button-secondary" type="button" onClick={retry}>Try Again</button></section> : !impact ? <section className="analysis-card empty-analysis"><h2>No challenge found.</h2><Link className="button button-primary" to="/submit">Submit a Challenge</Link></section> : <><div className="impact-dashboard"><section className="analysis-card impact-score-card"><p className="card-kicker">PROTOTYPE IMPACT SCORE</p><strong>{impact.score} <small>/ 100</small></strong><span className={`impact-level impact-${impact.level.toLowerCase()}`}>{impact.level.toUpperCase()} IMPACT</span><p>This score is deterministic prototype guidance, not a scientifically validated prediction.</p></section><section className="analysis-card impact-factors"><h2>Impact Factors</h2>{Object.entries(impact.factors).map(([key, value]) => <div className="factor-row" key={key}><div><span>{labels[key]}</span><strong>{value}%</strong></div><i><b style={{ width: `${value}%` }} /></i></div>)}</section><section className="analysis-card why-card"><h2>Why this challenge matters</h2><p>{explanation}</p></section><section className="analysis-card pipeline-card"><h2>Impact Pipeline</h2><div className="impact-pipeline">{['Problem Understood', 'Category Identified', 'Similar Problems Checked'].map((item) => <span key={item}><CheckCircle2 size={16} />{item}</span>)}<span className="current"><CircleDashed size={16} />Impact Assessed</span><span className="future"><CircleDashed size={16} />Collaboration Matching</span></div></section></div><div className="analysis-actions"><Link className="button button-secondary" to="/similar"><ArrowLeft size={16} />Back to Similar Challenges</Link><Link className="button button-primary" to="/solutions">Explore Solution Directions <ArrowRight size={16} /></Link></div></>}</main></div>
}
export default Impact
