import { ArrowLeft, ArrowRight, Building2, LoaderCircle } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import Navbar from '../components/Navbar'
import { getIndustryMatches } from '../services/api'
function Industry() {
 const [challenge]=useState(()=>JSON.parse(sessionStorage.getItem('neuroxChallenge')||'null')); const [matches,setMatches]=useState([]); const [loading,setLoading]=useState(Boolean(challenge)); const [error,setError]=useState('')
 const load=useCallback(async()=>{if(!challenge)return;setError('');try{const data=await getIndustryMatches(challenge);setMatches(data.matches||[])}catch{setError('Industry matching is temporarily unavailable.')}finally{setLoading(false)}},[challenge]); useEffect(()=>{const t=window.setTimeout(load,0);return()=>window.clearTimeout(t)},[load]); const retry=()=>{setLoading(true);load()}
 return <div className="app-shell form-shell"><Navbar/><main className="analysis-page container"><Link className="back-link" to="/universities"><ArrowLeft size={16}/>Back to Universities</Link><div className="analysis-heading"><p className="eyebrow"><span/>INDUSTRY COLLABORATION</p><h1>Potential technology and resource partners.</h1><p>Potential collaborators based on the challenge requirements.</p></div><p className="demo-note">These are prototype matches using demo industry data. They do not represent confirmed partnerships.</p>{loading?<section className="analysis-card loading-card"><LoaderCircle className="spinner" size={30}/><h2>NeuroX is matching demo organizations...</h2></section>:error?<section className="analysis-card empty-analysis"><h2>{error}</h2><p>Please try again.</p><button className="button button-secondary" onClick={retry}>Retry</button></section>:!challenge?<section className="analysis-card empty-analysis"><h2>No challenge found.</h2><Link className="button button-primary" to="/submit">Submit a Challenge</Link></section>:<><div className="university-grid">{matches.map(item=><article className="analysis-card university-card" key={item.id}><Building2 size={22}/><span className="demo-badge">DEMO DATA</span><h2>{item.name}</h2><strong className="match-score">{item.match_score}% Match</strong><p><b>Capabilities:</b> {item.matching_capabilities.join(' • ')}</p><p><b>Potential Support:</b> {item.support_types.join(' • ')}</p><div className="match-breakdown"><span>Domain Match <b>{item.score_breakdown.domain}/40</b></span><span>Capability Match <b>{item.score_breakdown.capability}/35</b></span><span>Support Match <b>{item.score_breakdown.support}/25</b></span><strong>Overall Match {item.match_score}%</strong></div></article>)}</div><div className="analysis-actions"><Link className="button button-secondary" to="/universities"><ArrowLeft size={16}/>Back to Universities</Link><Link className="button button-primary" to="/workspace">Build Solution Workspace <ArrowRight size={16}/></Link></div></>}</main></div>
}
export default Industry
