import { ArrowLeft, BrainCircuit, LoaderCircle } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import Navbar from '../components/Navbar'
import { submitChallenge as sendChallenge } from '../services/api'

const initialForm = { title: '', description: '', domain: '', location: '', affectedPeople: '' }
const domains = ['Water & Sanitation', 'Waste Management', 'Healthcare', 'Transportation', 'Education', 'Agriculture', 'Energy', 'Environment', 'Other']

function SubmitChallenge() {
  const [form, setForm] = useState(initialForm); const [errors, setErrors] = useState({}); const [loading, setLoading] = useState(false); const [apiError, setApiError] = useState(''); const navigate = useNavigate()
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value })
  const validate = () => { const next = {}; if (!form.title.trim()) next.title = 'Challenge title is required.'; if (!form.description.trim()) next.description = 'Please describe the problem.'; if (!form.domain) next.domain = 'Please select a domain.'; if (!form.location.trim()) next.location = 'Location is required.'; setErrors(next); return Object.keys(next).length === 0 }
  const submit = async (event) => { event.preventDefault(); setApiError(''); if (!validate()) return; setLoading(true); try { const response = await sendChallenge(form); sessionStorage.setItem('neuroxChallenge', JSON.stringify(response.challenge)); sessionStorage.setItem('neuroxAiAnalysis', JSON.stringify(response.ai_analysis || {})); sessionStorage.removeItem('neuroxAnalysisReady'); navigate('/analysis') } catch { setApiError('Unable to connect to NeuroX AI services. Please make sure the NeuroX backend is running.'); setLoading(false) } }
  return <div className="app-shell form-shell"><Navbar /><main className="form-page container"><Link className="back-link" to="/"><ArrowLeft size={16} />Back to Challenge Hub</Link><div className="form-heading"><p className="eyebrow"><span />NEW SOCIETAL CHALLENGE</p><h1>Describe a Problem. <span>Start a Solution.</span></h1><p>Tell NeuroX about a real-world societal challenge. Our AI will analyze the problem and help identify relevant opportunities for collaboration.</p></div><form className="challenge-form" onSubmit={submit} noValidate>{apiError && <div className="api-error" role="alert">{apiError}<button type="submit">Try Again</button></div>}<div className="form-grid"><label>Challenge Title<input name="title" value={form.title} onChange={update} placeholder="e.g. Public water taps are causing unnecessary water wastage" aria-invalid={Boolean(errors.title)} />{errors.title && <small className="field-error">{errors.title}</small>}</label><label>Problem Domain<select name="domain" value={form.domain} onChange={update} aria-invalid={Boolean(errors.domain)}><option value="">Select a domain</option>{domains.map((domain) => <option key={domain}>{domain}</option>)}</select>{errors.domain && <small className="field-error">{errors.domain}</small>}</label></div><label>Describe the Problem<textarea name="description" value={form.description} onChange={update} maxLength={1000} rows={7} placeholder="Describe the societal problem, who is affected, what is happening, and why it matters..." aria-invalid={Boolean(errors.description)} /><span className="char-count">{form.description.length} / 1000</span>{errors.description && <small className="field-error">{errors.description}</small>}</label><div className="form-grid"><label>Location<input name="location" value={form.location} onChange={update} placeholder="e.g. Nashik, Maharashtra" aria-invalid={Boolean(errors.location)} />{errors.location && <small className="field-error">{errors.location}</small>}</label><label>Who is affected? <em>Optional</em><textarea name="affectedPeople" value={form.affectedPeople} onChange={update} rows={3} placeholder="e.g. Residents of nearby villages and local water authorities" /></label></div><button className="button button-primary analyze-cta" disabled={loading} type="submit">{loading ? <><LoaderCircle className="spinner" size={18} />Analyzing Challenge...</> : <><BrainCircuit size={18} />Analyze with NeuroX AI</>}</button><p className="form-note">Your submission is sent to the local NeuroX prototype backend.</p></form></main></div>
}
export default SubmitChallenge
